# Generated by Django 6.0.1 on 2026-01-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineBatchMentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Full_Name', models.CharField(help_text='Your Full Name ..', max_length=50)),
                ('Designation', models.CharField(help_text='Your Current Job Position ..', max_length=50)),
                ('Email', models.CharField(help_text='Enter Unique E-mail Address ..', max_length=50, unique=True)),
                ('Photo', models.ImageField(help_text='Your Photo ..', upload_to='Images')),
                ('Phone_Number', models.CharField(help_text='Enter Phone Number ..', max_length=11, unique=True)),
                ('Salary', models.DecimalField(decimal_places=2, help_text='Your Current Salary ..', max_digits=50)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
